[package]
name = "harborctl"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "btrfs-harborctl"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
harbor-core = { path = "../harbor-core" }
harbor-engine = { path = "../harbor-engine" }
harbor-recovery = { path = "../harbor-recovery" }
harbor-replica = { path = "../harbor-replica" }
harbor-storage = { path = "../harbor-storage" }
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
uuid.workspace = true
